spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/demo
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true

jwt.secret=sistema-creditos-dev-secret-key-change-me-0123456789
jwt.expiration-ms=900000


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
