export enum ApiStatusCode {
  UserCreated = 'ACCT-001',
  LoginSuccess = 'ACCT-002',
  InvalidCredentials = 'ACCT-003',
  UserAlreadyExists = 'ACCT-004',
  InvalidToken = 'ACCT-006',
  InvalidUserData = 'ACCT-007',
  CreditSuccess = 'TRX-000',
  CreditCreated = 'TRX-001',
  CreditStatusUpdated = 'TRX-002',
  InvalidAmount = 'TRX-003',
  InvalidTerm = 'TRX-004',
  InvalidCreditStatus = 'TRX-005',
  CreditNotFound = 'TRX-006',
  CreditAlreadyProcessed = 'TRX-007',
  InvalidCreditData = 'TRX-008',
  InternalError = 'TRX-999',
}
